import os
p = os.path.join("C:", os.sep, "Users", "Owner", "Desktop", "claude code", "contact-dashboard", "email_inspectors.py")
L = []
L.append('')
L.append('')
L.append('# ==============================================================================')
L.append('# AGENT 4: Formatting Inspector')
L.append('# ==============================================================================')
L.append('def inspect_formatting(email_dict):')
L.append('    """Validates HTML structure, CTA, length, signature."""')
L.append('    issues = []')
L.append('    score = 100')
L.append('    body_html = email_dict.get("body_html") or ""')
L.append('    body_text = email_dict.get("body_text") or _strip_html(body_html)')
L.append('    email_stage = (email_dict.get("email_stage") or "intro").strip().lower()')
L.append('')
L.append('    for tag in ["p", "div", "table", "tr", "td", "ul", "li", "strong", "em"]:')
L.append('        opens = len(re.findall(r"<%s[\\s>]" % tag, body_html, re.IGNORECASE))')
L.append('        closes = len(re.findall(r"</%s>" % tag, body_html, re.IGNORECASE))')
L.append('        if opens > closes + 2:')
L.append('            issues.append("Unclosed <%s> tags" % tag)')
L.append('            score -= 5')
L.append('')
L.append('    has_cta = bool(re.search(')
L.append('        r\'<a\\s+[^>]*style="[^"]*display:\\s*inline-block[^"]*background[^"]*"\',')
L.append('        body_html, re.IGNORECASE))')
L.append('    if not has_cta:')
L.append('        has_cta = bool(re.search(')
L.append('            r\'<a\\s+[^>]*style="[^"]*padding[^"]*border-radius[^"]*"\',')
L.append('            body_html, re.IGNORECASE))')
L.append('    if not has_cta and email_stage == "intro":')
L.append('        issues.append("No CTA button in intro email")')
L.append('        score -= 15')
L.append('')
L.append('    if has_cta:')
L.append('        m = re.search(r\'<a\\s+[^>]*style="[^"]*padding\', body_html, re.IGNORECASE)')
L.append('        if m:')
L.append('            before = body_html[:m.start()]')
L.append("            pc = len(re.findall(r'<p[\\s>]', before, re.IGNORECASE))")
L.append('            if pc > 6:')
L.append('                issues.append("%d paragraphs before CTA" % pc)')
L.append('                score -= 5')
L.append('')
L.append("    for s in re.findall(r'font-size:\\s*(\\d+)px', body_html):")
L.append('        if int(s) < 10:')
L.append('            issues.append("Font %spx too small" % s)')
L.append('            score -= 5')
L.append('')
L.append('    for href in re.findall(r\'<a\\s+[^>]*href="([^"]*)"\', body_html, re.IGNORECASE):')
L.append('        if not href or href == "#" or href.startswith("javascript:"):')
L.append('            issues.append("Invalid href: %s" % href)')
L.append('            score -= 5')
L.append('')
L.append('    wc = _word_count(body_text)')
L.append('    mx = {"intro": 250, "follow_up": 200, "rate_request": 200,')
L.append('          "engaged": 200, "re_engagement": 200}.get(email_stage, 250)')
L.append('    if wc > mx:')
L.append('        issues.append("%d words (max %d)" % (wc, mx))')
L.append('        score -= 10')
L.append('')
L.append('    if not any(p in body_html.lower() for p in')
L.append('               ["flash cargo global", "flashcargoglobal.com", "worldwide freight"]):')
L.append('        issues.append("No signature block")')
L.append('        score -= 10')
L.append('')
L.append("    if body_text and re.search(r'<[a-zA-Z][^>]*>', body_text):")
L.append('        issues.append("Raw HTML in plain text")')
L.append('        score -= 10')
L.append('')
L.append('    return {"pass": score >= 60, "issues": issues, "score": max(0, score)}')
with open(p, "a", encoding="utf-8", newline=chr(10)) as out:
    out.write(chr(10).join(L) + chr(10))
print("Agent 4 done")
