"""
TMS Integration Hub
One-click connect to every major logistics platform worldwide.
From our end: enter key → connected. Delay only if the third party doesn't want to connect.
"""

INTEGRATIONS = {
    # ── LOAD BOARDS (North America) ─────────────────────────────────────────
    "dat": {
        "name": "DAT Freight & Analytics",
        "category": "Load Board",
        "region": "North America",
        "logo": "https://www.dat.com/favicon.ico",
        "color": "#e63946",
        "description": "Largest freight marketplace in North America. Post loads, find carriers, access rate data.",
        "website": "https://www.dat.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"}],
        "docs": "https://developer.dat.com",
        "capabilities": ["Load posting", "Rate lookup", "Carrier search", "Market data"],
    },
    "truckstop": {
        "name": "Truckstop.com",
        "category": "Load Board",
        "region": "North America",
        "logo": "https://truckstop.com/favicon.ico",
        "color": "#f77f00",
        "description": "Trusted freight marketplace connecting brokers and carriers across North America.",
        "website": "https://truckstop.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "username", "label": "Username", "type": "text"}],
        "docs": "https://developer.truckstop.com",
        "capabilities": ["Load board", "Rate analytics", "Carrier vetting", "DOT lookup"],
    },

    # ── CARRIER VETTING / SAFETY ─────────────────────────────────────────────
    "highway": {
        "name": "Highway",
        "category": "Carrier Vetting",
        "region": "North America",
        "logo": "https://www.highway.com/favicon.ico",
        "color": "#4cc9f0",
        "description": "AI-powered carrier identity and fraud prevention. Verify carriers instantly.",
        "website": "https://www.highway.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://docs.highway.com",
        "capabilities": ["Carrier identity", "Fraud detection", "DOT/MC lookup", "Insurance verification"],
    },
    "carrier_assure": {
        "name": "Carrier Assure",
        "category": "Carrier Vetting",
        "region": "North America",
        "logo": "https://carrierassure.com/favicon.ico",
        "color": "#06d6a0",
        "description": "Predictive carrier safety scoring. Know carrier risk before you book.",
        "website": "https://carrierassure.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "account_id", "label": "Account ID", "type": "text"}],
        "docs": "https://carrierassure.com/api",
        "capabilities": ["Safety scoring", "Risk assessment", "Accident history", "Real-time alerts"],
    },
    "rmis": {
        "name": "RMIS (Carrier Onboarding)",
        "category": "Carrier Vetting",
        "region": "North America",
        "logo": "https://www.rmissolutions.com/favicon.ico",
        "color": "#7209b7",
        "description": "Industry-standard carrier onboarding, monitoring, and compliance management.",
        "website": "https://www.rmissolutions.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://www.rmissolutions.com/api",
        "capabilities": ["Carrier onboarding", "Insurance monitoring", "Compliance", "Authority checks"],
    },
    "mycarrierpackets": {
        "name": "My Carrier Packets",
        "category": "Carrier Vetting",
        "region": "North America",
        "logo": "",
        "color": "#3a86ff",
        "description": "Digital carrier packets and onboarding automation for freight brokers.",
        "website": "https://www.mycarrierpackets.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "company_id", "label": "Company ID", "type": "text"}],
        "docs": "https://www.mycarrierpackets.com/api",
        "capabilities": ["Digital packets", "E-signature", "Insurance verification", "Carrier database"],
    },

    # ── VISIBILITY & TRACKING ────────────────────────────────────────────────
    "project44": {
        "name": "project44",
        "category": "Visibility",
        "region": "Global",
        "logo": "https://www.project44.com/favicon.ico",
        "color": "#ff6b6b",
        "description": "Global supply chain visibility platform. Real-time tracking across all modes.",
        "website": "https://www.project44.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"},
                   {"key": "client_secret", "label": "Client Secret", "type": "password"}],
        "docs": "https://developer.project44.com",
        "capabilities": ["Real-time tracking", "ETA prediction", "Ocean/air/road", "Event alerts"],
    },
    "fourkites": {
        "name": "FourKites",
        "category": "Visibility",
        "region": "Global",
        "logo": "https://www.fourkites.com/favicon.ico",
        "color": "#118ab2",
        "description": "AI-powered real-time supply chain visibility across ocean, road, rail, and air.",
        "website": "https://www.fourkites.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://developer.fourkites.com",
        "capabilities": ["Predictive ETA", "Multi-modal tracking", "Exception management", "Analytics"],
    },
    "macropoint": {
        "name": "MacroPoint (Descartes)",
        "category": "Visibility",
        "region": "North America",
        "logo": "https://www.macropoint.com/favicon.ico",
        "color": "#06aed5",
        "description": "Automated freight tracking and carrier visibility network.",
        "website": "https://www.macropoint.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "username", "label": "Username", "type": "text"}],
        "docs": "https://www.macropoint.com/api",
        "capabilities": ["GPS tracking", "Automated check-calls", "ETA updates", "Exception alerts"],
    },

    # ── GLOBAL TMS / FREIGHT PLATFORMS ──────────────────────────────────────
    "cargowise": {
        "name": "CargoWise",
        "category": "Global TMS",
        "region": "Global",
        "logo": "https://www.cargowise.com/favicon.ico",
        "color": "#e63946",
        "description": "World's leading logistics execution platform. Used by top freight forwarders globally.",
        "website": "https://www.cargowise.com",
        "fields": [{"key": "api_key", "label": "API Key / Integration Key", "type": "password"},
                   {"key": "server_url", "label": "Server URL", "type": "text"},
                   {"key": "username", "label": "Username", "type": "text"}],
        "docs": "https://www.cargowise.com/integration",
        "capabilities": ["Shipment sync", "Customs", "Accounting", "Document exchange"],
    },
    "flexport": {
        "name": "Flexport",
        "category": "Digital Freight",
        "region": "Global",
        "logo": "https://www.flexport.com/favicon.ico",
        "color": "#5e60ce",
        "description": "Digital freight forwarder and supply chain platform with full API coverage.",
        "website": "https://www.flexport.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://apidocs.flexport.com",
        "capabilities": ["Booking", "Tracking", "Documentation", "Rate quotes"],
    },
    "freightos": {
        "name": "Freightos",
        "category": "Rate Marketplace",
        "region": "Global",
        "logo": "https://www.freightos.com/favicon.ico",
        "color": "#f72585",
        "description": "Global freight rate marketplace. Instant quotes from hundreds of carriers.",
        "website": "https://www.freightos.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"}],
        "docs": "https://dev.freightos.com",
        "capabilities": ["Instant quotes", "Multi-carrier compare", "Booking", "Tracking"],
    },

    # ── OCEAN CARRIERS ───────────────────────────────────────────────────────
    "maersk": {
        "name": "Maersk API",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.maersk.com/favicon.ico",
        "color": "#00243d",
        "description": "Direct API to world's largest shipping line for schedules, tracking, and booking.",
        "website": "https://developer.maersk.com",
        "fields": [{"key": "api_key", "label": "Consumer Key", "type": "password"},
                   {"key": "api_secret", "label": "Consumer Secret", "type": "password"}],
        "docs": "https://developer.maersk.com",
        "capabilities": ["Vessel schedules", "Container tracking", "Rate quotes", "BL management"],
    },
    "msc": {
        "name": "MSC",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.msc.com/favicon.ico",
        "color": "#003087",
        "description": "Direct integration with MSC for schedules, tracking, and shipping instructions.",
        "website": "https://www.msc.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "account_id", "label": "Account ID", "type": "text"}],
        "docs": "https://www.msc.com/api",
        "capabilities": ["Schedules", "Tracking", "SI submission", "Rate management"],
    },
    "cma_cgm": {
        "name": "CMA CGM",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.cma-cgm.com/favicon.ico",
        "color": "#e63946",
        "description": "Direct API connection to CMA CGM for ocean freight schedules and tracking.",
        "website": "https://apis.cma-cgm.net",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"}],
        "docs": "https://apis.cma-cgm.net",
        "capabilities": ["Schedules", "Container tracking", "Rate quotes", "Booking"],
    },
    "hapag_lloyd": {
        "name": "Hapag-Lloyd",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.hapag-lloyd.com/favicon.ico",
        "color": "#f77f00",
        "description": "Connect directly to Hapag-Lloyd for rates, schedules, and container tracking.",
        "website": "https://www.hapag-lloyd.com/en/online-business/connect/hapag-lloyd-api.html",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://www.hapag-lloyd.com/en/online-business/connect/hapag-lloyd-api.html",
        "capabilities": ["Schedules", "Tracking", "Rate request", "BL management"],
    },
    "one_line": {
        "name": "ONE (Ocean Network Express)",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.one-line.com/favicon.ico",
        "color": "#e63946",
        "description": "ONE's digital API for schedule lookup, tracking, and documentation.",
        "website": "https://www.one-line.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "account_no", "label": "Account Number", "type": "text"}],
        "docs": "https://www.one-line.com/en/our-services/ecommerce",
        "capabilities": ["Vessel schedules", "Container tracking", "SI/BL", "Rate quotes"],
    },
    "evergreen": {
        "name": "Evergreen Line",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.evergreen-line.com/favicon.ico",
        "color": "#2dc653",
        "description": "Evergreen API for container tracking, schedules, and documentation.",
        "website": "https://www.evergreen-line.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "customer_code", "label": "Customer Code", "type": "text"}],
        "docs": "https://www.evergreen-line.com/eline/api",
        "capabilities": ["Tracking", "Schedules", "SI submission", "Arrival notice"],
    },
    "cosco": {
        "name": "COSCO Shipping",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.cosco-usa.com/favicon.ico",
        "color": "#e63946",
        "description": "COSCO Shipping Lines API for bookings, tracking, and documentation.",
        "website": "https://www.cosco-usa.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "account_id", "label": "Account ID", "type": "text"}],
        "docs": "https://elines.coscoshipping.com/ebusiness",
        "capabilities": ["Booking", "Tracking", "Schedules", "BL management"],
    },
    "zim": {
        "name": "ZIM",
        "category": "Ocean Carrier",
        "region": "Global",
        "logo": "https://www.zim.com/favicon.ico",
        "color": "#e63946",
        "description": "ZIM Integrated Shipping API for tracking, booking, and rate management.",
        "website": "https://www.zim.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://www.zim.com/tools/api-services",
        "capabilities": ["Tracking", "Schedules", "Booking", "Rate quotes"],
    },

    # ── CUSTOMS & COMPLIANCE ─────────────────────────────────────────────────
    "descartes": {
        "name": "Descartes Systems",
        "category": "Customs & Compliance",
        "region": "Global",
        "logo": "https://www.descartes.com/favicon.ico",
        "color": "#4361ee",
        "description": "Global compliance, customs filing, and trade intelligence platform.",
        "website": "https://www.descartes.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "server_url", "label": "Server URL", "type": "text"}],
        "docs": "https://www.descartes.com/resources/api",
        "capabilities": ["Customs filing", "Denied party screening", "Trade compliance", "Route optimization"],
    },
    "inttra": {
        "name": "INTTRA (E2open)",
        "category": "Ocean Network",
        "region": "Global",
        "logo": "",
        "color": "#560bad",
        "description": "World's largest ocean shipping network. Connect to carriers and NVOCCs.",
        "website": "https://www.inttra.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "username", "label": "INTTRA Username", "type": "text"}],
        "docs": "https://www.inttra.com/developers",
        "capabilities": ["Booking", "SI", "BL", "Vessel schedule", "Track & trace"],
    },

    # ── NORTH AMERICA SPECIFIC ───────────────────────────────────────────────
    "uber_freight": {
        "name": "Uber Freight",
        "category": "Digital Broker",
        "region": "North America",
        "logo": "https://www.uberfreight.com/favicon.ico",
        "color": "#000000",
        "description": "Instant freight pricing and carrier matching across North America.",
        "website": "https://www.uberfreight.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"}],
        "docs": "https://developer.uberfreight.com",
        "capabilities": ["Instant rates", "Carrier matching", "Load tracking", "Payment"],
    },
    "rose_rocket": {
        "name": "Rose Rocket",
        "category": "TMS",
        "region": "North America",
        "logo": "https://www.roserocket.com/favicon.ico",
        "color": "#e63946",
        "description": "Modern TMS for freight brokers and carriers. Sync shipments bidirectionally.",
        "website": "https://www.roserocket.com",
        "fields": [{"key": "api_key", "label": "API Token", "type": "password"},
                   {"key": "org_slug", "label": "Organization Slug", "type": "text"}],
        "docs": "https://developer.roserocket.com",
        "capabilities": ["Order sync", "Carrier dispatch", "Invoicing", "Customer portal"],
    },
    "turvo": {
        "name": "Turvo",
        "category": "TMS",
        "region": "North America",
        "logo": "https://turvo.com/favicon.ico",
        "color": "#7209b7",
        "description": "Collaborative TMS and freight marketplace platform.",
        "website": "https://turvo.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://developer.turvo.com",
        "capabilities": ["Shipment management", "Carrier collaboration", "Rate management", "Analytics"],
    },
    "mcleod": {
        "name": "McLeod Software",
        "category": "TMS",
        "region": "North America",
        "logo": "",
        "color": "#3a86ff",
        "description": "Enterprise TMS for carriers and brokers. Sync loads and carrier data.",
        "website": "https://www.mcleodsoftware.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "server_url", "label": "Server URL", "type": "text"}],
        "docs": "https://www.mcleodsoftware.com/integration",
        "capabilities": ["Load management", "Carrier dispatch", "Billing", "Driver management"],
    },

    # ── AIR FREIGHT ──────────────────────────────────────────────────────────
    "cargo_ai": {
        "name": "Cargo.AI",
        "category": "Air Freight",
        "region": "Global",
        "logo": "",
        "color": "#118ab2",
        "description": "AI-driven air cargo marketplace. Instant air freight rates and booking.",
        "website": "https://cargo.ai",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://cargo.ai/api",
        "capabilities": ["Air freight rates", "Booking", "Tracking", "Schedule lookup"],
    },
    "webcargo": {
        "name": "WebCargo by Freightos",
        "category": "Air Freight",
        "region": "Global",
        "logo": "",
        "color": "#f72585",
        "description": "Digital air cargo booking platform connecting forwarders to airlines.",
        "website": "https://www.webcargo.net",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "agent_code", "label": "Agent IATA Code", "type": "text"}],
        "docs": "https://developer.webcargo.net",
        "capabilities": ["Air rates", "AWB issuance", "Tracking", "Airline connections"],
    },

    # ── PAYMENTS & FINANCE ───────────────────────────────────────────────────
    "triumph_pay": {
        "name": "TriumphPay",
        "category": "Freight Finance",
        "region": "North America",
        "logo": "",
        "color": "#06d6a0",
        "description": "Freight-specific payment network. Fast carrier payments and invoice factoring.",
        "website": "https://www.triumphpay.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"},
                   {"key": "client_id", "label": "Client ID", "type": "text"}],
        "docs": "https://developer.triumphpay.com",
        "capabilities": ["Carrier payments", "Invoice factoring", "QuickPay", "Audit"],
    },
    "apex_capital": {
        "name": "Apex Capital (Factoring)",
        "category": "Freight Finance",
        "region": "North America",
        "logo": "",
        "color": "#ffd166",
        "description": "Freight invoice factoring and fuel card network for carriers.",
        "website": "https://www.apexcapitalcorp.com",
        "fields": [{"key": "api_key", "label": "API Key", "type": "password"}],
        "docs": "https://www.apexcapitalcorp.com/api",
        "capabilities": ["Invoice factoring", "Fuel cards", "Credit checks", "Payment tracking"],
    },
}


def get_categories():
    """Return unique categories with counts."""
    cats = {}
    for k, v in INTEGRATIONS.items():
        c = v['category']
        cats[c] = cats.get(c, 0) + 1
    return cats


def get_by_category():
    """Return integrations grouped by category."""
    groups = {}
    for k, v in INTEGRATIONS.items():
        c = v['category']
        if c not in groups:
            groups[c] = []
        groups[c].append({**v, 'id': k})
    return groups
