"""
TMS Document Generator — Global
Generates BOL, Commercial Invoice, Packing List, and POD PDFs.
Supports any currency, language hint, and international port/address.
"""
import base64
import io
import os
from datetime import datetime

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import Image as ReportLabImage
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    from reportlab.lib.enums import TA_CENTER, TA_RIGHT

    REPORTLAB_AVAILABLE = True
except ImportError:
    colors = None
    A4 = (612, 792)
    getSampleStyleSheet = None
    ParagraphStyle = None
    mm = 72 / 25.4
    SimpleDocTemplate = None
    Spacer = None
    Table = None
    TableStyle = None
    Paragraph = None
    ReportLabImage = None
    TA_CENTER = 1
    TA_RIGHT = 2
    REPORTLAB_AVAILABLE = False

# ── Palette ────────────────────────────────────────────────────────────────────
if REPORTLAB_AVAILABLE:
    DARK = colors.HexColor("#0d1117")
    BLUE = colors.HexColor("#0d6efd")
    LIGHT = colors.HexColor("#f8f9fa")
    GREY = colors.HexColor("#6c757d")
    WHITE = colors.white
    BLACK = colors.black
else:
    DARK = BLUE = LIGHT = GREY = WHITE = BLACK = None


def _escape_pdf_text(value):
    return (
        str(value or "")
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _text_pdf(title, lines):
    safe_lines = [title] + [line for line in lines if line]
    commands = ["BT", "/F1 18 Tf", "50 780 Td", f"({_escape_pdf_text(safe_lines[0])}) Tj"]
    commands.extend(["/F1 10 Tf", "0 -24 Td"])

    for index, line in enumerate(safe_lines[1:]):
        if index > 0:
            commands.append("0 -14 Td")
        commands.append(f"({_escape_pdf_text(line)}) Tj")
    commands.append("ET")
    content_stream = "\n".join(commands).encode("latin-1", "replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        f"<< /Length {len(content_stream)} >>\nstream\n".encode("ascii") + content_stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_start = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF".encode(
            "ascii"
        )
    )
    return bytes(pdf)


def _fallback_document_lines(shipment, company_name, document_type):
    return [
        company_name,
        f"Shipment Reference: {shipment.get('shipment_ref', 'N/A')}",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        f"Shipper: {shipment.get('shipper_name', '-')}",
        f"Consignee: {shipment.get('consignee_name', '-')}",
        f"Origin: {shipment.get('origin_port', '-')}",
        f"Destination: {shipment.get('destination_port', '-')}",
        f"Status: {shipment.get('status', 'Draft')}",
        f"Cargo: {shipment.get('cargo_description', '-')}",
        f"Containers: {shipment.get('containers', '-')}",
        f"Weight (kg): {shipment.get('weight_kg') or 0}",
        f"Volume (cbm): {shipment.get('volume_cbm') or 0}",
        f"Freight Rate: {shipment.get('currency', 'USD')} {float(shipment.get('freight_rate') or 0):,.2f}",
        f"Incoterm: {shipment.get('incoterm', 'FOB')}",
        "",
        f"{document_type} generated by the TMS fallback PDF renderer.",
    ]


def _decode_signature_image(signature_data):
    raw_value = str(signature_data or "").strip()
    if not raw_value or "," not in raw_value:
        return None

    try:
        _, encoded = raw_value.split(",", 1)
        return io.BytesIO(base64.b64decode(encoded))
    except (ValueError, TypeError, base64.binascii.Error):
        return None


def _photo_image_stream(photo_path):
    clean_path = str(photo_path or "").strip()
    if not clean_path or not os.path.exists(clean_path):
        return None
    try:
        with open(clean_path, "rb") as handle:
            return io.BytesIO(handle.read())
    except OSError:
        return None

# ── Helpers ───────────────────────────────────────────────────────────────────
def _styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle('Title2',   fontName='Helvetica-Bold', fontSize=18, textColor=DARK,  spaceAfter=2))
    s.add(ParagraphStyle('Sub',      fontName='Helvetica',      fontSize=9,  textColor=GREY,  spaceAfter=2))
    s.add(ParagraphStyle('Label',    fontName='Helvetica-Bold', fontSize=8,  textColor=GREY))
    s.add(ParagraphStyle('Value',    fontName='Helvetica',      fontSize=9,  textColor=DARK))
    s.add(ParagraphStyle('Bold9',    fontName='Helvetica-Bold', fontSize=9,  textColor=DARK))
    s.add(ParagraphStyle('Center9',  fontName='Helvetica',      fontSize=9,  textColor=DARK,  alignment=TA_CENTER))
    s.add(ParagraphStyle('Right9',   fontName='Helvetica',      fontSize=9,  textColor=DARK,  alignment=TA_RIGHT))
    s.add(ParagraphStyle('Small',    fontName='Helvetica',      fontSize=7,  textColor=GREY))
    return s

def _tbl_style(header_bg=BLUE):
    return TableStyle([
        ('BACKGROUND', (0,0), (-1,0), header_bg),
        ('TEXTCOLOR',  (0,0), (-1,0), WHITE),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [WHITE, LIGHT]),
        ('GRID',       (0,0), (-1,-1), 0.4, colors.HexColor('#dee2e6')),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
    ])

def _header_table(s, company_name, doc_type, ref, date_str, color=BLUE):
    """Top banner with company name left, document type right."""
    data = [[
        Paragraph(f'<font color="#0d6efd"><b>{company_name}</b></font>', s['Title2']),
        Paragraph(f'<b>{doc_type}</b><br/><font color="#6c757d">{ref}</font><br/><font color="#6c757d">{date_str}</font>', s['Right9'])
    ]]
    t = Table(data, colWidths=[95*mm, 95*mm])
    t.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LINEBELOW', (0,0), (-1,-1), 1.2, color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    return t

def _party_table(s, shipper_name, shipper_addr, consignee_name, consignee_addr):
    data = [
        [Paragraph('SHIPPER / EXPORTER', s['Label']), Paragraph('CONSIGNEE / IMPORTER', s['Label'])],
        [Paragraph(shipper_name or '—', s['Bold9']),   Paragraph(consignee_name or '—', s['Bold9'])],
        [Paragraph(shipper_addr or '',  s['Value']),   Paragraph(consignee_addr or '',  s['Value'])],
    ]
    t = Table(data, colWidths=[95*mm, 95*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), LIGHT),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 8),
        ('BOX',        (0,0), (-1,-1), 0.5, colors.HexColor('#dee2e6')),
        ('LINEAFTER',  (0,0), (0,-1), 0.5, colors.HexColor('#dee2e6')),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
    ]))
    return t


# ── BOL ───────────────────────────────────────────────────────────────────────
def generate_bol(shipment: dict, company_name='My Freight Co') -> bytes:
    if not REPORTLAB_AVAILABLE:
        return _text_pdf("Bill of Lading", _fallback_document_lines(shipment, company_name, "Bill of Lading"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    s   = _styles()
    ref = shipment.get('shipment_ref', 'N/A')
    now = datetime.utcnow().strftime('%Y-%m-%d')
    story = []

    story.append(_header_table(s, company_name, 'BILL OF LADING', f'BOL# {ref}', f'Date: {now}'))
    story.append(Spacer(1, 5*mm))
    story.append(_party_table(s,
        shipment.get('shipper_name'),    shipment.get('shipper_address'),
        shipment.get('consignee_name'),  shipment.get('consignee_address')))
    story.append(Spacer(1, 4*mm))

    # Route info
    route_data = [
        ['PORT OF LOADING', 'PORT OF DISCHARGE', 'CARRIER', 'ETD', 'ETA', 'INCOTERM'],
        [
            shipment.get('origin_port', '—'),
            shipment.get('destination_port', '—'),
            shipment.get('carrier_name', '—'),
            shipment.get('etd', '—'),
            shipment.get('eta', '—'),
            shipment.get('incoterm', 'FOB'),
        ]
    ]
    rt = Table(route_data, colWidths=[35*mm, 35*mm, 35*mm, 25*mm, 25*mm, 35*mm])
    rt.setStyle(_tbl_style())
    story.append(rt)
    story.append(Spacer(1, 4*mm))

    # Cargo
    cargo_data = [
        ['DESCRIPTION OF GOODS', 'CONTAINER/MARKS', 'WEIGHT (KG)', 'VOLUME (CBM)'],
        [
            shipment.get('cargo_description', '—'),
            shipment.get('containers', '—'),
            f"{shipment.get('weight_kg') or 0:,.1f}",
            f"{shipment.get('volume_cbm') or 0:,.2f}",
        ]
    ]
    ct = Table(cargo_data, colWidths=[70*mm, 50*mm, 30*mm, 30*mm-4])
    ct.setStyle(_tbl_style())
    story.append(ct)
    story.append(Spacer(1, 8*mm))

    # Freight charges
    freight = shipment.get('freight_rate') or 0
    currency = shipment.get('currency', 'USD')
    charge_data = [
        ['FREIGHT CHARGES', 'CURRENCY', 'AMOUNT', 'PAYMENT TERMS'],
        ['Ocean Freight', currency, f'{freight:,.2f}', 'PREPAID'],
    ]
    cht = Table(charge_data, colWidths=[70*mm, 30*mm, 40*mm, 50*mm])
    cht.setStyle(_tbl_style())
    story.append(cht)
    story.append(Spacer(1, 8*mm))

    # Signature boxes
    sig_data = [[
        Paragraph('SHIPPER SIGNATURE\n\n\n\n________________________', s['Small']),
        Paragraph('CARRIER SIGNATURE\n\n\n\n________________________', s['Small']),
        Paragraph('CONSIGNEE SIGNATURE\n\n\n\n________________________', s['Small']),
    ]]
    st = Table(sig_data, colWidths=[63*mm, 63*mm, 64*mm])
    st.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 0.5, GREY),
        ('LINEBEFORE', (1,0), (2,-1), 0.5, GREY),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(st)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph('This document is issued subject to applicable international conventions and carrier tariffs. | Generated by TMS', s['Small']))

    doc.build(story)
    return buf.getvalue()


# ── COMMERCIAL INVOICE ────────────────────────────────────────────────────────
def generate_invoice(shipment: dict, company_name='My Freight Co') -> bytes:
    if not REPORTLAB_AVAILABLE:
        return _text_pdf("Commercial Invoice", _fallback_document_lines(shipment, company_name, "Commercial Invoice"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    s   = _styles()
    ref      = shipment.get('shipment_ref', 'N/A')
    currency = shipment.get('currency', 'USD')
    freight  = float(shipment.get('freight_rate') or 0)
    now      = datetime.utcnow().strftime('%Y-%m-%d')
    story    = []

    story.append(_header_table(s, company_name, 'COMMERCIAL INVOICE', f'INV# {ref}', f'Date: {now}', BLUE))
    story.append(Spacer(1, 5*mm))
    story.append(_party_table(s,
        shipment.get('shipper_name'),    shipment.get('shipper_address'),
        shipment.get('consignee_name'),  shipment.get('consignee_address')))
    story.append(Spacer(1, 4*mm))

    # Shipment meta
    meta = [
        ['COUNTRY OF ORIGIN', 'COUNTRY OF DESTINATION', 'INCOTERM', 'PAYMENT CURRENCY'],
        [
            shipment.get('origin_port', '—'),
            shipment.get('destination_port', '—'),
            shipment.get('incoterm', 'FOB'),
            currency,
        ]
    ]
    mt = Table(meta, colWidths=[47*mm, 50*mm, 35*mm, 58*mm])
    mt.setStyle(_tbl_style())
    story.append(mt)
    story.append(Spacer(1, 4*mm))

    # Line items
    items_data = [
        ['#', 'DESCRIPTION', 'CONTAINERS', 'WEIGHT (KG)', 'UNIT PRICE', 'TOTAL'],
        [
            '1',
            shipment.get('cargo_description', 'Freight Services'),
            shipment.get('containers', '—'),
            f"{shipment.get('weight_kg') or 0:,.1f}",
            f'{currency} {freight:,.2f}',
            f'{currency} {freight:,.2f}',
        ],
    ]
    it = Table(items_data, colWidths=[8*mm, 60*mm, 32*mm, 28*mm, 30*mm, 32*mm])
    it.setStyle(_tbl_style())
    story.append(it)
    story.append(Spacer(1, 3*mm))

    # Totals
    totals_data = [
        ['', '', '', '', 'SUBTOTAL:', f'{currency} {freight:,.2f}'],
        ['', '', '', '', 'TAX / VAT:', f'{currency} 0.00'],
        ['', '', '', '', 'TOTAL DUE:', f'{currency} {freight:,.2f}'],
    ]
    tot = Table(totals_data, colWidths=[8*mm, 60*mm, 32*mm, 28*mm, 30*mm, 32*mm])
    tot.setStyle(TableStyle([
        ('FONTNAME',  (4,2), (5,2), 'Helvetica-Bold'),
        ('FONTSIZE',  (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 3),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ('LINEABOVE', (4,2), (5,2), 1, BLUE),
        ('ALIGN', (4,0), (5,-1), 'RIGHT'),
    ]))
    story.append(tot)
    story.append(Spacer(1, 8*mm))

    story.append(Paragraph('<b>Declaration:</b> The undersigned declares that the information on this invoice is complete and correct.', s['Small']))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph('Authorised Signature: ________________________      Date: ___________', s['Small']))

    doc.build(story)
    return buf.getvalue()


# ── PACKING LIST ──────────────────────────────────────────────────────────────
def generate_packing_list(shipment: dict, company_name='My Freight Co') -> bytes:
    if not REPORTLAB_AVAILABLE:
        return _text_pdf("Packing List", _fallback_document_lines(shipment, company_name, "Packing List"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    s   = _styles()
    ref = shipment.get('shipment_ref', 'N/A')
    now = datetime.utcnow().strftime('%Y-%m-%d')
    story = []

    story.append(_header_table(s, company_name, 'PACKING LIST', f'PL# {ref}', f'Date: {now}', BLUE))
    story.append(Spacer(1, 5*mm))
    story.append(_party_table(s,
        shipment.get('shipper_name'),    shipment.get('shipper_address'),
        shipment.get('consignee_name'),  shipment.get('consignee_address')))
    story.append(Spacer(1, 4*mm))

    # Container/shipping marks
    marks_data = [
        ['SHIPPING MARKS', 'CONTAINER DETAILS', 'PORT OF LOADING', 'PORT OF DISCHARGE'],
        [
            ref,
            shipment.get('containers', '—'),
            shipment.get('origin_port', '—'),
            shipment.get('destination_port', '—'),
        ]
    ]
    mt = Table(marks_data, colWidths=[42*mm, 45*mm, 43*mm, 60*mm])
    mt.setStyle(_tbl_style())
    story.append(mt)
    story.append(Spacer(1, 4*mm))

    # Packing detail
    pack_data = [
        ['PKG#', 'DESCRIPTION', 'QTY', 'GROSS WEIGHT (KG)', 'NET WEIGHT (KG)', 'VOLUME (CBM)'],
        [
            '1',
            shipment.get('cargo_description', '—'),
            '1',
            f"{shipment.get('weight_kg') or 0:,.1f}",
            f"{(float(shipment.get('weight_kg') or 0) * 0.95):,.1f}",
            f"{shipment.get('volume_cbm') or 0:,.2f}",
        ],
        ['', 'TOTAL', '', f"{shipment.get('weight_kg') or 0:,.1f}", '', f"{shipment.get('volume_cbm') or 0:,.2f}"],
    ]
    pt = Table(pack_data, colWidths=[12*mm, 60*mm, 12*mm, 35*mm, 35*mm, 36*mm])
    pt.setStyle(TableStyle([
        *_tbl_style().getCommands(),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), LIGHT),
    ]))
    story.append(pt)
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph(
        'This packing list is for customs and shipping reference only. All weights are approximate. '
        'Generated by TMS — global freight management system.',
        s['Small']))

    doc.build(story)
    return buf.getvalue()


def generate_pod(shipment: dict, pod_record: dict, company_name='My Freight Co') -> bytes:
    pod_record = pod_record or {}
    if not REPORTLAB_AVAILABLE:
        lines = _fallback_document_lines(shipment, company_name, "Proof of Delivery")
        lines.extend(
            [
                "",
                f"Recipient: {pod_record.get('recipient_name') or '-'}",
                f"Delivered At: {pod_record.get('delivered_at') or '-'}",
                f"Notes: {pod_record.get('notes') or '-'}",
            ]
        )
        return _text_pdf("Proof of Delivery", lines)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )
    s = _styles()
    ref = shipment.get("shipment_ref", "N/A")
    delivered_at = (pod_record.get("delivered_at") or "").strip() or "-"
    story = []

    story.append(_header_table(s, company_name, 'PROOF OF DELIVERY', f'POD# {ref}', f'Delivered: {delivered_at}', BLUE))
    story.append(Spacer(1, 5 * mm))
    story.append(_party_table(s,
        shipment.get('shipper_name'), shipment.get('shipper_address'),
        shipment.get('consignee_name'), shipment.get('consignee_address')))
    story.append(Spacer(1, 4 * mm))

    summary = Table(
        [
            ['SHIPMENT REF', 'RECIPIENT', 'DELIVERY STATUS', 'DELIVERED AT'],
            [
                ref,
                pod_record.get('recipient_name') or '-',
                shipment.get('status') or 'Delivered',
                delivered_at,
            ],
        ],
        colWidths=[38 * mm, 56 * mm, 42 * mm, 54 * mm],
    )
    summary.setStyle(_tbl_style())
    story.append(summary)
    story.append(Spacer(1, 4 * mm))

    notes = pod_record.get('notes') or 'No delivery notes provided.'
    notes_table = Table(
        [
            [Paragraph('DELIVERY NOTES', s['Label'])],
            [Paragraph(notes.replace('\n', '<br/>'), s['Value'])],
        ],
        colWidths=[190 * mm],
    )
    notes_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(notes_table)
    story.append(Spacer(1, 6 * mm))

    signature_stream = _decode_signature_image(pod_record.get('signature_data'))
    if signature_stream:
        signature_table = Table(
            [
                [Paragraph('RECIPIENT SIGNATURE', s['Label'])],
                [ReportLabImage(signature_stream, width=75 * mm, height=24 * mm)],
            ],
            colWidths=[190 * mm],
        )
        signature_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(signature_table)
        story.append(Spacer(1, 4 * mm))

    photo_stream = _photo_image_stream(pod_record.get('photo_path'))
    if photo_stream:
        photo_table = Table(
            [
                [Paragraph('DELIVERY PHOTO', s['Label'])],
                [ReportLabImage(photo_stream, width=75 * mm, height=56 * mm)],
            ],
            colWidths=[190 * mm],
        )
        photo_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(photo_table)
        story.append(Spacer(1, 4 * mm))

    story.append(Paragraph(
        'Proof of delivery generated from the mobile POD workflow. Signature and photo are captured at submission time.',
        s['Small']))

    doc.build(story)
    return buf.getvalue()


# ── AIR WAYBILL ───────────────────────────────────────────────────────────────
def _awb_number(shipment_ref: str) -> str:
    """Generate a deterministic AWB number in format XXX-XXXXXXXX from shipment ref."""
    import hashlib as _hashlib
    digest = _hashlib.md5(str(shipment_ref).encode()).hexdigest()
    prefix = str(int(digest[:6], 16) % 1000).zfill(3)
    suffix = str(int(digest[6:14], 16) % 100000000).zfill(8)
    return f"{prefix}-{suffix}"


def generate_awb(shipment: dict, company_name='My Freight Co') -> bytes:
    if not REPORTLAB_AVAILABLE:
        return _text_pdf("Air Waybill", _fallback_document_lines(shipment, company_name, "Air Waybill"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    s   = _styles()
    ref      = shipment.get('shipment_ref', 'N/A')
    awb_num  = _awb_number(ref)
    now      = datetime.utcnow().strftime('%Y-%m-%d')
    currency = shipment.get('currency', 'USD')
    freight  = float(shipment.get('freight_rate') or 0)
    weight   = float(shipment.get('weight_kg') or 0)
    declared = f"{currency} {freight:,.2f}" if freight else "NVD"
    story    = []

    story.append(_header_table(s, company_name, 'AIR WAYBILL', f'AWB# {awb_num}', f'Issue Date: {now}', BLUE))
    story.append(Spacer(1, 5*mm))

    # Shipper / Consignee
    story.append(_party_table(s,
        shipment.get('shipper_name'),   shipment.get('shipper_address'),
        shipment.get('consignee_name'), shipment.get('consignee_address')))
    story.append(Spacer(1, 4*mm))

    # Routing
    route_data = [
        ['ISSUING CARRIER', 'DEPARTURE AIRPORT', 'DESTINATION AIRPORT', 'FLIGHT / ETD', 'INCOTERM'],
        [
            shipment.get('carrier_name', '—'),
            shipment.get('origin_port', '—'),
            shipment.get('destination_port', '—'),
            shipment.get('etd', '—'),
            shipment.get('incoterm', 'DAP'),
        ]
    ]
    rt = Table(route_data, colWidths=[38*mm, 37*mm, 40*mm, 37*mm, 28*mm-4])
    rt.setStyle(_tbl_style())
    story.append(rt)
    story.append(Spacer(1, 4*mm))

    # Cargo details
    chargeable = round(max(weight, (float(shipment.get('volume_cbm') or 0) * 167)), 1)
    rate_per_kg = round(freight / chargeable, 4) if chargeable else 0.0
    cargo_data = [
        ['PIECES', 'NATURE OF GOODS', 'GROSS WEIGHT (KG)', 'CHARGEABLE WT (KG)', 'RATE/KG', 'TOTAL'],
        [
            '1',
            shipment.get('cargo_description', '—'),
            f"{weight:,.1f}",
            f"{chargeable:,.1f}",
            f"{currency} {rate_per_kg:,.4f}",
            f"{currency} {freight:,.2f}",
        ]
    ]
    ct = Table(cargo_data, colWidths=[14*mm, 56*mm, 32*mm, 32*mm, 28*mm, 28*mm])
    ct.setStyle(_tbl_style())
    story.append(ct)
    story.append(Spacer(1, 4*mm))

    # Charges
    fuel_surcharge = round(freight * 0.15, 2)
    total_charges  = round(freight + fuel_surcharge, 2)
    charge_data = [
        ['CHARGE TYPE', 'CURRENCY', 'AMOUNT'],
        ['Air Freight',   currency, f'{freight:,.2f}'],
        ['Fuel Surcharge (15%)', currency, f'{fuel_surcharge:,.2f}'],
        ['TOTAL CHARGES', currency, f'{total_charges:,.2f}'],
    ]
    cht = Table(charge_data, colWidths=[100*mm, 40*mm, 50*mm])
    cht.setStyle(TableStyle([
        *_tbl_style().getCommands(),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), LIGHT),
    ]))
    story.append(cht)
    story.append(Spacer(1, 4*mm))

    # Declared value + special handling
    meta_data = [
        ['DECLARED VALUE FOR CUSTOMS', 'SPECIAL HANDLING / NOTES'],
        [declared, shipment.get('notes', '') or 'None'],
    ]
    mt = Table(meta_data, colWidths=[95*mm, 95*mm])
    mt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), LIGHT),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 8),
        ('BOX',        (0,0), (-1,-1), 0.5, colors.HexColor('#dee2e6')),
        ('LINEAFTER',  (0,0), (0,-1), 0.5, colors.HexColor('#dee2e6')),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
    ]))
    story.append(mt)
    story.append(Spacer(1, 8*mm))

    # Signature boxes
    sig_data = [[
        Paragraph('SHIPPER SIGNATURE\n\n\n\n________________________', s['Small']),
        Paragraph('CARRIER SIGNATURE\n\n\n\n________________________', s['Small']),
        Paragraph('DATE\n\n\n\n________________________', s['Small']),
    ]]
    st = Table(sig_data, colWidths=[63*mm, 63*mm, 64*mm])
    st.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 0.5, GREY),
        ('LINEBEFORE', (1,0), (2,-1), 0.5, GREY),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(st)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        'This Air Waybill is a non-negotiable transport document issued under IATA conditions. '
        'Chargeable weight = greater of actual gross weight or volumetric weight (volume cbm × 167). '
        '| Generated by TMS',
        s['Small']))

    doc.build(story)
    return buf.getvalue()


def generate_customer_invoice(invoice: dict, shipment: dict, company_name='My Freight Co') -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    s = _styles()

    invoice_id = int(invoice.get('id') or 0)
    invoice_number = f"CINV-{invoice_id:05d}" if invoice_id else f"CINV-{shipment.get('shipment_ref', 'N/A')}"
    invoice_date = (invoice.get('created_at') or '').strip()[:10] or datetime.utcnow().strftime('%Y-%m-%d')
    due_date = (invoice.get('due_date') or '').strip()[:10] or '-'
    paid_at = (invoice.get('paid_at') or '').strip()[:10] or '-'
    customer_name = invoice.get('customer_name') or shipment.get('shipper_name') or '-'
    if customer_name == shipment.get('consignee_name'):
        customer_address = shipment.get('consignee_address') or ''
    else:
        customer_address = shipment.get('shipper_address') or ''

    status = invoice.get('status') or 'Draft'
    currency = invoice.get('currency') or shipment.get('currency') or 'USD'
    amount = float(invoice.get('amount') or 0)
    exchange_rate = float(invoice.get('exchange_rate') or 1)
    route_label = f"{shipment.get('origin_port') or '-'} -> {shipment.get('destination_port') or '-'}"
    story = []

    story.append(_header_table(s, company_name, 'CUSTOMER INVOICE', invoice_number, f'Date: {invoice_date}', BLUE))
    story.append(Spacer(1, 5*mm))

    parties = Table(
        [
            [Paragraph('ISSUED BY', s['Label']), Paragraph('BILLED TO', s['Label'])],
            [Paragraph(company_name or '-', s['Bold9']), Paragraph(customer_name, s['Bold9'])],
            [
                Paragraph('Freight services invoice', s['Value']),
                Paragraph(customer_address, s['Value']),
            ],
        ],
        colWidths=[95*mm, 95*mm],
    )
    parties.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), LIGHT),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
        ('LINEAFTER', (0, 0), (0, -1), 0.5, colors.HexColor('#dee2e6')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(parties)
    story.append(Spacer(1, 4*mm))

    meta = [
        ['SHIPMENT REF', 'STATUS', 'DUE DATE', 'PAID AT', 'EXCHANGE RATE'],
        [
            shipment.get('shipment_ref', '-'),
            status,
            due_date,
            paid_at,
            f"{exchange_rate:,.4f}",
        ],
    ]
    meta_table = Table(meta, colWidths=[42*mm, 32*mm, 34*mm, 34*mm, 48*mm])
    meta_table.setStyle(_tbl_style())
    story.append(meta_table)
    story.append(Spacer(1, 4*mm))

    items = [
        ['#', 'DESCRIPTION', 'ROUTE', 'CONTAINERS', 'TOTAL'],
        [
            '1',
            shipment.get('cargo_description', 'Freight services'),
            route_label,
            shipment.get('containers', '-') or '-',
            f'{currency} {amount:,.2f}',
        ],
    ]
    items_table = Table(items, colWidths=[8*mm, 60*mm, 52*mm, 32*mm, 38*mm])
    items_table.setStyle(_tbl_style())
    story.append(items_table)
    story.append(Spacer(1, 3*mm))

    totals = [
        ['', '', '', 'SUBTOTAL:', f'{currency} {amount:,.2f}'],
        ['', '', '', 'TOTAL DUE:', f'{currency} {amount:,.2f}'],
    ]
    totals_table = Table(totals, colWidths=[8*mm, 60*mm, 52*mm, 32*mm, 38*mm])
    totals_table.setStyle(TableStyle([
        ('FONTNAME', (3, 1), (4, 1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LINEABOVE', (3, 1), (4, 1), 1, BLUE),
        ('ALIGN', (3, 0), (4, -1), 'RIGHT'),
    ]))
    story.append(totals_table)
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph(
        'Customer invoice generated from shipment data. Exchange rate is recorded for accounting sync.',
        s['Small']))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph('Authorised Signature: ________________________      Date: ___________', s['Small']))

    doc.build(story)
    return buf.getvalue()
